[project]
site_name = "PlotJS"
repo_url = "https://github.com/y-sunflower/plotjs"
site_url = "https://y-sunflower.github.io/plotjs/"
site_description = "Turn static matplotlib charts into interactive web visualizations"
site_author = "Joseph Barbier"
copyright = """
Copyright &copy; 2026 Yellow Sunflower
"""
extra_css = ["stylesheets/style.css"]
nav = [
  { "Home" = "index.md" },
  { "Gallery" = "gallery/index.md" },
  { "Guides" = [
    "guides/index.md",
    "guides/css/index.md",
    "guides/javascript/index.md",
    "guides/embed-graphs/index.md",
    "guides/troubleshooting/index.md",
    "guides/advanced/index.md",
  ] },
  { "API Reference" = [
    "reference/plotjs.md",
    "reference/css.md",
    "reference/javascript.md",
    "reference/datasets.md",
  ] },
  { "For developers" = [
    "developers/overview.md",
    "developers/parsing-matplotlib-svg.md",
    "developers/svg-parser-reference.md",
    "developers/contributing.md",
  ] },
]

[project.theme]
language = "en"
favicon = "images/favicon.png"
custom_dir = "overrides"
logo = "https://github.com/JosephBARBIERDARNAL/static/blob/main/python-libs/plotjs/image.png?raw=true"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
favicon = "https://github.com/JosephBARBIERDARNAL/static/blob/main/python-libs/plotjs/favicon.ico?raw=true"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["."]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false
